name: Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  renovate:
    name: Renovate Sync
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub App Bot
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.PROJECT_APP_ID }}
          private-key: ${{ secrets.PROJECT_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Install Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.27.0"
          cache: true
          cache-dependency-path: "**/*.sum"

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "24.x"

      - name: Run Renovate
        run: task deps:renovate:sync
        env:
          ## Discovery
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          ## Project sync
          RENOVATE_PLATFORM: "github"
          RENOVATE_PLATFORM_COMMIT: "enabled"
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_COM_TOKEN: ${{ steps.app-token.outputs.token }}
          # Remove unused fields from PR description
          RENOVATE_PR_BODY_TEMPLATE: "{{{header}}}{{{table}}}{{{warnings}}}{{{notes}}}{{{changelogs}}}"
          RENOVATE_DEPENDENCY_DASHBOARD_HEADER: ""
          RENOVATE_DEPENDENCY_DASHBOARD_O_S_V_VULNERABILITY_SUMMARY: "all"
