# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Test E2E Cross-Platform

on:
  workflow_call:

jobs:
  cross-platform:
    name: Cross-Platform Test ${{ matrix.label }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            label: Linux
          - runner: macos-latest
            label: macOS
          - runner: windows-latest
            label: Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0

      - name: Setup Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.27.0"
          cache-dependency-path: "**/*.sum"
          cache: true

      - name: Run daemon smoke tests
        run: |
          task e2e:test:daemon:default
