# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      image_tag:
        required: true
        type: string
        description: "Image tag to use."
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.27.0"
          cache-dependency-path: "**/*.sum"
          cache: true # NOTE: Default value, just to be explicit

      - name: Generate coverage report
        run: |
          task test:unit:coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-unit
          path: .coverage/**/*.out
          include-hidden-files: true
          retention-days: 1

      - name: Run unit tests
        run: |
          task test:unit

  e2e:
    name: E2E
    uses: ./.github/workflows/reusable-test-e2e.yaml
    with:
      image_repo: ${{ inputs.image_repo }}
      image_tag: ${{ inputs.image_tag }}
