# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."

jobs:
  image:
    name: Image
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_repo: ${{ inputs.image_repo }}
      image_tag: ${{ inputs.release_tag }}
      push: true

  chart:
    name: Helm chart
    uses: ./.github/workflows/reusable-release-helm.yaml
    with:
      image_repo: ${{ inputs.image_repo }}
      release_tag: ${{ inputs.release_tag }}

  cli:
    name: CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.27.0"
          cache-dependency-path: "**/*.sum"
          cache: true # NOTE: Default value, just to be explicit

      - name: Build
        run: |
          task cli:compile:all

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cli-artifacts
          path: .bin
          if-no-files-found: error
          include-hidden-files: true

  release:
    name: Release
    needs:
      - image
      - chart
      - cli
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release_tag }}
          name: Release ${{ inputs.release_tag }}
          draft: true
          prerelease: false

  upload:
    name: Upload Asset
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        if: ${{ !(contains(matrix.os, 'windows') && contains(matrix.arch, 'arm64')) }}
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Download CLI artifacts
        if: ${{ !(contains(matrix.os, 'windows') && contains(matrix.arch, 'arm64')) }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cli-artifacts
          path: .bin

      - name: Verify file
        if: ${{ !(contains(matrix.os, 'windows') && contains(matrix.arch, 'arm64')) }}
        run: |
          ls -l .bin
          file .bin/dirctl-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload CLI Release Asset
        if: ${{ !(contains(matrix.os, 'windows') && contains(matrix.arch, 'arm64')) }}
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release_tag }}
          files: .bin/dirctl-${{ matrix.os }}-${{ matrix.arch }}
          append_body: true
          draft: true
